### PR TITLE
Browser compatibility

### PR DESCRIPTION
**Pull request by vespakoen**
This should add it

EDIT: This won't add it, I guess I will make a "fs" folder in node_modules and export an empty object

### CODE REVIEW

**Comment by feross** [comment]
@vespakoen `pump` should work just fine in the browser. `require('fs')` will return an empty object in the browser.

**Comment by vespakoen** [comment]
True, but not with react-native (issue title is incorrect)
Got it working with the node_modules/fs/index.js file having `module.exports = {};` in it.

**Comment by feross** [comment]
Weird. What does `react-native` do differently?

**Comment by vespakoen** [comment]
It throws an error saying it cannot find the fs module.
The react-native-packager is a bit stupid sometimes =\

**Comment by feross** [comment]
Sounds like this should be fixed there, not here. Maybe open an issue on their repo?

**Comment by mafintosh** [comment]
does the react thing set process.browser like browserify does?

**Comment by feross** [comment]
@mafintosh i think browserify does special stuff for built-ins modules like `fs`. Wouldn't the react thing just need to special case all the built-ins?

**Comment by vespakoen** [comment]
There are already a couple of issues that are related:

https://github.com/facebook/react-native/issues/5079
https://github.com/facebook/react-native/issues/5917
https://github.com/facebook/react-native/issues/5555
https://github.com/facebook/react-native/issues/1871

React native now supports the "browser" and "react-native" field in a package.json, so you could shim it with an empty object for react-native only.

I believe the best solution would be for the react-native packager to use browserify's shims for the node packages

**Comment by mafintosh** [comment]
we can probably get rid of the require fs line as well and check for some file related properties on the stream

**Comment by mafintosh** [comment]
@feross yea that would work as well.

**Pull request closed without merging**
