### PR TITLE
(breaking) remove return of pipeline - closes #9

### LINKED ISSUE #9: Consider returning undefined instead of a stream
I found it very counter-intuitive that this module returns a stream but it doesn't propagate errors to it.  Would you consider not returning the produced stream?

### PR DESCRIPTION
**Pull request by phated**
Wasn't sure the best way to test this change.  Labelled the commit as breaking and semver should be bumped major.

### CODE REVIEW

**Comment by fractalawareness** [comment]
Any progress on this?

**Comment by phated** [comment]
Hey @mafintosh, just wanted to ping this again.  Thoughts?

**Comment by phated** [comment]
@mafintosh following up again. Think this can be shipped?

**Comment by phated** [comment]
@mafintosh what do you think?

**Comment by marshall007** [comment]
@phated can you elaborate on why returning `undefined` is preferable over propagating `error` events on the returned stream? It wasn't clear from #9 how we reached that conclusion. Given that it's a breaking change either way, I would much prefer the latter.

**Comment by phated** [comment]
@marshall007 If you propagate the errors to the returned stream, this module basically just becomes `pumpify`.  I think it better for there to be a clear separation between the modules; however, I'm open to whatever solution will resolve this problem.

**Comment by marshall007** [comment]
@phated my main argument would be that it seems reasonable to assume that `pump`'ing together an already `pump`'d readable stream should produce the same callback result as if you pumped them flatly in a single call.

I think returning `undefined` would make this module much less useful. While I agree it creates ambiguity with `pumpify`, the key difference is that `pump` takes a readable stream as its first argument.

**Comment by phated** [comment]
In my interpretation, `pump` is supposed to take the `readable` and `writable` ends of a pipeline (and optionally everything in between) and "pump" them upon construction.  I think it should be considered improper usage to give it a readable + some transforms and expect to use that later.  Again, that can (and should?) be achieved by `pumpify`.  I believe pumpify can take a readable as the first argument also (pretty sure I've used it like that before).

**Comment by marshall007** [comment]
> I believe pumpify can take a readable as the first argument also (pretty sure I've used it like that before).

@phated sorry for the delay. I just got around to trying this and it didn't seem to work. Passing a readable stream as the first argument appears to return an empty readable stream.

**Comment by phated** [comment]
@marshall007 I'm not sure what your test looked like but this works as I decribed:
```js
var pumpify = require('pumpify')
var from = require('from2')
var through = require('through2')
var to = require('to2')

var str = pumpify(from(['1','2','3']), through(function(chunk, _, cb){
 cb(null, chunk)
}));

str.pipe(to(function(chunk, _, cb) {
  console.log(chunk.toString());
  cb()
}))
```

**Comment by phated** [comment]
ping @mafintosh

**Comment by mafintosh** [comment]
@phated sorry i was being slow. gonna release this now!

**Comment by mafintosh** [comment]
2.0.0

**Comment by phated** [comment]
Thanks @mafintosh!!!!

**Pull request merged**
